[project]
name = "zadanie-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.129.0",
    "joblib",
    "matplotlib>=3.10.8",
    "numpy",
    "pandas",
    "scikit-learn",
    "seaborn>=0.13.2",
    "uvicorn>=0.40.0",
]
